FROM tmcglinn/ave:latest

# AdaBots
COPY AdaBots_examples /adabots_examples
WORKDIR "/adabots_examples"
RUN alr build

# Alire environment for adabots, generated by running bash in ave and then: alr printenv > src/file.sh
ENV AAA_ALIRE_PREFIX "/adabots_examples/alire/cache/dependencies/aaa_0.2.6_dfd6339b"
ENV ADABOTS_ALIRE_PREFIX "/adabots_examples/alire/cache/dependencies/adabots_1.2.0_f8238a93"
ENV ADABOTS_EXAMPLES_ALIRE_PREFIX "/adabots_examples"
ENV ALIRE "True"
ENV AWS_ALIRE_PREFIX "/adabots_examples/alire/cache/dependencies/aws_21.0.0_57fddf8f"
ENV GNAT_NATIVE_ALIRE_PREFIX "/root/.config/alire/cache/dependencies/gnat_native_11.2.4_2f37a10b"
ENV GPRBUILD_ALIRE_PREFIX "/root/.config/alire/cache/dependencies/gprbuild_22.0.1_24dfc1b5"
ENV GPR_PROJECT_PATH "/adabots_examples:/adabots_examples/alire/cache/dependencies/aaa_0.2.6_dfd6339b:/adabots_examples/alire/cache/dependencies/adabots_1.2.0_f8238a93:/adabots_examples/alire/cache/dependencies/aws_21.0.0_57fddf8f/install_dir/share/gpr:/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890/distrib:/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890/dom:/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890/input_sources:/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890/sax:/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890/schema:/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890/unicode:/root/.config/alire/cache/dependencies/gnat_native_11.2.4_2f37a10b:/root/.config/alire/cache/dependencies/gprbuild_22.0.1_24dfc1b5"
ENV MAKE_ALIRE_PREFIX "/adabots_examples/alire/cache/dependencies/make_4.2.1_system"
ENV PATH "/root/.config/alire/cache/dependencies/gprbuild_22.0.1_24dfc1b5/bin:/root/.config/alire/cache/dependencies/gnat_native_11.2.4_2f37a10b/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV PRJ_LAL "Disabled"
ENV PRJ_TARGET "UNIX"
ENV TARGET "x86_64-linux-gnu"
ENV XMLADA_ALIRE_PREFIX "/adabots_examples/alire/cache/dependencies/xmlada_21.0.0_836d1890"

# Nvim plugins
COPY /vimrc/abe_plugins.vim /vimrc/
RUN echo '\n" ABE plugins\nsource /vimrc/abe_plugins.vim' >> /vimrc/plugins.vim
RUN nvim -u '/vimrc/plug_framework.vim' -c 'PlugInstall' -c 'qall!'

# Ada snippets
COPY /snippets/ada.snippets /snippets/
RUN cat /snippets/ada.snippets >> /root/.vim/plugged/vim-snippets/UltiSnips/ada.snippets

# Remove ctrl-space mapping from AVE
RUN sed -i 's/.*cmp.mapping.complete/-- removed complete/' /root/.config/nvim/lua/custom_lspconfig.lua

# ABE file templates
COPY /templates/ /abe_templates/

# Nvim configuration
COPY /vimrc/ /vimrc/
RUN echo '\n" ABE config\nsource /vimrc/abe_config.vim' >> /vimrc/vimrc.vim

# Copy version info file
COPY version /
